version: "3.9"

services:
  web:
    build: .
    container_name: task_project_web
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://task_user:task_pass@db:5432/task_db
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: task_project_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: task_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
